<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/proto/friends.proto

namespace GPBMetadata\Resources\Proto;

class Friends
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ë
resources/proto/friends.protoFriendsService"3
 GetFriendRequestsByUserIdRequest
user_id ("„
!GetFriendRequestsByUserIdResponse6
friend_requests (2.FriendsService.FriendRequest\'
friends (2.FriendsService.Friend"1
FriendRequest

id (
requester_id ("
Friend
FriendId (2“
FriendsService€
GetFriendRequestsByUserId0.FriendsService.GetFriendRequestsByUserIdRequest1.FriendsService.GetFriendRequestsByUserIdResponseBÊFriendsServicebproto3'
        , true);

        static::$is_initialized = true;
    }
}

