services:
  rabbitmq:
    image: "rabbitmq:3.13-management"
    container_name: rabbitmq-app
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./init.sh:/init.sh
    networks:
      - elk
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    entrypoint: >
      bash -c "
      rabbitmq-server &
      sleep 10 && ./init.sh &
      wait"

networks:
  elk:
    external: true
