<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/proto/friends.proto

namespace FriendsService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FriendsService.Friend</code>
 */
class Friend extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 FriendId = 1;</code>
     */
    protected $FriendId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $FriendId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Proto\Friends::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 FriendId = 1;</code>
     * @return int
     */
    public function getFriendId()
    {
        return $this->FriendId;
    }

    /**
     * Generated from protobuf field <code>int32 FriendId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFriendId($var)
    {
        GPBUtil::checkInt32($var);
        $this->FriendId = $var;

        return $this;
    }

}

