<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/proto/friends.proto

namespace FriendsService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FriendsService.FriendRequest</code>
 */
class FriendRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int32 requester_id = 2;</code>
     */
    protected $requester_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type int $requester_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Proto\Friends::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 requester_id = 2;</code>
     * @return int
     */
    public function getRequesterId()
    {
        return $this->requester_id;
    }

    /**
     * Generated from protobuf field <code>int32 requester_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRequesterId($var)
    {
        GPBUtil::checkInt32($var);
        $this->requester_id = $var;

        return $this;
    }

}

