<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/proto/friends.proto

namespace FriendsService;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FriendsService.GetFriendRequestsByUserIdResponse</code>
 */
class GetFriendRequestsByUserIdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .FriendsService.FriendRequest friend_requests = 1;</code>
     */
    private $friend_requests;
    /**
     * Generated from protobuf field <code>repeated .FriendsService.Friend friends = 2;</code>
     */
    private $friends;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\FriendsService\FriendRequest>|\Google\Protobuf\Internal\RepeatedField $friend_requests
     *     @type array<\FriendsService\Friend>|\Google\Protobuf\Internal\RepeatedField $friends
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Proto\Friends::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .FriendsService.FriendRequest friend_requests = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriendRequests()
    {
        return $this->friend_requests;
    }

    /**
     * Generated from protobuf field <code>repeated .FriendsService.FriendRequest friend_requests = 1;</code>
     * @param array<\FriendsService\FriendRequest>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriendRequests($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FriendsService\FriendRequest::class);
        $this->friend_requests = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .FriendsService.Friend friends = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFriends()
    {
        return $this->friends;
    }

    /**
     * Generated from protobuf field <code>repeated .FriendsService.Friend friends = 2;</code>
     * @param array<\FriendsService\Friend>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFriends($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FriendsService\Friend::class);
        $this->friends = $arr;

        return $this;
    }

}

