services:
  front:
    container_name: front-app

    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      composer install --no-interaction --optimize-autoloader &&
      npm install &&
      npm run build &&
      php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8000:8000